### ISSUE TITLE
App Page · remove title bars

### ISSUE THREAD

**Issue by federicca** [civic-commons/opencivic#40]
Remove "screenshots" "videos" "photos" title bars from App page

**Comment by fusionx1** [comment]
this has been fixed, but due to breakdown of my mac's battery i wasnt able to push it on github

**Comment by fusionx1** [comment]
fixed

**Comment by sheldonrampton** [comment]
I'm still seeing a "Video" title bar on the Drupal page: http://apps-cat.nuamsdev.com/app/drupal

**Comment by fusionx1** [comment]
its showing even if theres no video attached. I just fixed it will not show without attached video

**Comment by pmackay** [comment]
The whole Photos and videos section is set to Hidden currently under Application > Manage display. Is that intended?
